build.py
This is to accommodate work directories with spaces in the name. I encountered this issue earlier today.
Note: This fix is untested, because each time I run evobuild it redownloads ypkg in my chroot, overwriting edits I made. That said, putting quotes around an argument in 'cd' seems like something that at the very least won't break anything.
=> put quotes around %%workdir%% in line 159

scripts/ybump.py, scripts/yupdate.py
- The scripts ybump.py and yupdate.py import PyYAML, but did not use it.
- This update relies on ruamel.yaml version 0.11.10 to be installed
- Indentation/layout of YAML file is **exactly** preserved
- deprecated command.getoutput()  replaced by subprocess.check_output()
- print statements changed to print functions
- If the value for 'source' is the empty scalar (i.e. null) a sequence
will automatically be created as value
=> use parser for updating YAML files

ypkg2/rc.yml
So looking at the code changes this morning, you cut the / when you changed from %libdir%. This makes it --libexecdir=lib64valum from the build log and rebuilding it locally.
=> Amend libexecdir for meson

ypkg2/rc.yml
So I noticed qmake doesn't honour Solus flags. It takes the qmake flags set when building qt5. By default this is just -O2. Also doesn't honour LDFLAGS and so on. My research led to these flags and a test build using this line on ricochet, was honouring the Solus flags. 
The directories are still determined by what is set by Qt5 at build and that is likely the right thing as that's where it will search for them.
=> rc.yml: Add support for qmake packages

ypkg2/rc.yml
This macro operates identically to the Qt5 version, but it also overrides the paths to `moc`, `rcc`, and `uic`.
=> Added macro for Qt4

ypkg2/packages.py, ypkg2/rc.yml
These macros should make it considerably faster/easier to package Haskell libraries and development binaries:
* `cabal_configure`
Create a user package database, rebuild the 'package.cache' for `ghc`, then configure for a dynamically linked build
* `cabal_build`
Compile the source with %JOBS% processes
* `cabal_install`
Install the outputs to $installdir
* `cabal_register`
Generate the package.conf.d entry and install it
A pattern was also added to move the static libs into a -devel sub-package
**Caveat**
You must always install `ghc` and `haskell-cabal-install` for the macros to work.
=> Added Macros and Pattern for easy Haskell packaging

ypkg2/scripts.py
This fixes the Haskell macros. Apologies for not mentioning it in that PR.
=> Added ARCH macro to expose architecture to package.yml

ypkg2/ypkgcontext.py
New flag in GCC 7 -fprofile-update=atomic prevents creation of corrupted
profiles created during instrumentation, but with a speed penalty.
I don't see how this can be a bad thing! (I have tested it, and it does make it a little slower, but not a real concern)
=> context: Enable atomic updates for PGO generation

ypkg2/packages.py
QCH files are used with qt-creator and kdevelop, which are helpful only for
people developing on Solus. If they are building using a lib, they will need
the -devel package installed so they will also get these files. Want to move
them out of "main" as they can be significantly larger than the smaller
libraries themselves. Specific and higher priority to override the
/usr/share/doc rule already included.
Also removed duplicate vala pattern.
=> packages: Add pattern to move KDE dev docs to devel

ypkg2/rc.yml
Came across this when fixing x2goclient. It's not commonly used, but will fix
building on some packages.
=> rc: Add lrelease override for qmake4 macro

ypkg2/ypkgcontext.py, ypkg2/ypkgspec.py
Enable multiple optimizations to be listed and enable an easy lto and to unroll
loops (if ever needed) option for packages where it improves size/performance.
Perhaps not the most elegant python, but I know enough now to make any necessary changes to clang flags/ld to try and get it working better.
Has been tested in various multiple flag combinations on zlib.
=> ypkg2: Extend optimize to a list and add lto optimization

ypkg2/rc.yml
Currently we are unable to override flags in most builds (other than those
using autotools), making it a bit inflexible. This changes build flag options
to utilise the exported variable so it can be overriden in the package.yml.
=> rc: Use exported flag variables rather than macros

ypkg2/rc.yml
More ruby is starting to enter Solus, and currently they are all bundling their
own gems. This means if two packages use the same gem they conflict. This makes
it easy to package Rubygems so with start doing that instead (and it becomes
like perl/python with lots of little deps). It should also allow for networking
to be turned off for these packages. See T5014
It uses * to find the files as it will differ from the package name in many
cases (particularly where you need to add ruby-, but you can't remove it as
that breaks packages who's name uses ruby-). There should only be one per
package, but may be in different locations.
It may need some tweaks but will allow someone to start fixing up our ruby!
=> rc: Add support for easy rubygems

ypkg2/packages.py
Some sources utilise .pc files in /usr/share/pkgconfig/*.pc
This ensures that they are not included in the main package.
=> packages: Put straggling .pc files in devel package

ypkg2/rc.yml
Lessons learnt from packaging up a bunch of ruby gems to do so without turning
on networking.
- Add ability to specifiy .gemspec file (some have gemspecs for development
versions)
- Disable minimal dependency checking as it doesn't work as one would expect
Have been tested to build vagrant and the 35 gem deps all without networking.
=> rc: Fix ruby gem macros

man/package.yml.5, man/package.yml.5.html, man/package.yml.5.md, ypkg2/examine.py, ypkg2/scripts.py, ypkg2/ypkgcontext.py
The introduction of glibc-2.26 results in a change in directory for avx2
libraries. Glibc now uses the `haswell` directory, while the optimizations are
increased to `-march=haswell` to enable other math instructions that will
be present when the avx2 libraries are used.
=> Update avx2 build for glibc-2.26 changes

ypkg2/rc.yml
- also add `%ninja_build`, `%ninja_install` and `%ninja_check` macros that obsolete the corresponding `%meson` actionable macros.
Signed-off-by: Pierre-Yves <pyu@riseup.net>
=> New `%cmake_ninja` macro that can be combined with existing `%meson` macros

ypkg2/examine.py, ypkg2/scripts.py, ypkg2/ypkgcontext.py
Now uses gcc-{ar,ranlib,nm} which retains GIMPLE information. Updates support
for LTO with Clang and Gold linker to ensure the right flags are used.
=> Fix LTO builds after changes to the optimize key

ypkg2/rc.yml
Currently, GHC isn't doing code optimizations (default is -O0) or generating code with -FPIC. This fixes that by having Cabal set it at configure time.
=> Set GHC options in cabal_configure

ypkg2/rc.yml
No longer wants target ABI and architecture.
=> rc: Fix QML cache generation for Qt 5.11
